# Generated by Django 3.2.7 on 2021-09-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priyanshu', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
