# Generated by Django 3.2.7 on 2021-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priyanshu', '0008_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
